remote_theme: kosatyi/sjt

navigation: true
projects: true

baseurl: /ipsp-js-sdk

brand: IPSP JS SDK
title: IPSP JS SDK
description: Fondy Payment System
logo: fondy.svg

author:
  name: Fondy Developer Team
  url: https://fondy.eu/

toolbar:
  -
    name: Docs
    link: /docs/
  -
    name: Examples
    link: /examples/


#defaults:
#  -
#    scope:
#      path: ""
#      type: "pages"
#    values:
#      layout: default
#      image:
#        path:  /assets/img/cover.png
#        height: 1200
#        width: 630