gems:
  - jekyll-seo-tag

port: 4001

styles:
  - //fonts.googleapis.com/css?family=Open+Sans:300,400,700
  - /ipsp-js-sdk/assets/css/main.css

javascript:
  - /ipsp-js-sdk/assets/js/main.js

markdown: kramdown

title:        IPSP JS SDK
tagline:      In-page Checkout SDK
baseurl: /ipsp-js-sdk

author:
  name: Fondy Developer Team
  url: https://fondy.eu/

toolbar:


buttons:
  -
    name: View on GitHub
    link: https://github.com/cloudipsp/ipsp-js-sdk
  -
    name: Download .zip
    link: http://github.com/cloudipsp/ipsp-js-sdk/archive/master.zip
  -
    name: Download .tar.gz
    link: http://github.com/cloudipsp/ipsp-js-sdk/archive/master.tar.gz

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default