gems:
  - jekyll-seo-tag

port: 4001

styles:
  - //fonts.googleapis.com/css?family=Open+Sans:300,400,700
  - /assets/css/main.css

javascript:
  - /assets/js/main.js

markdown: kramdown


title:        Checkout Rocks
tagline:      In-page Checkout SDK
url:  https://checkout.rocks
baseurl:
banner:
  url: https://fondy.eu/
  image: /assets/img/banner.svg


facebook:
  publisher: https://www.facebook.com/ipsp.sdk/

author:
  name: Fondy Developer Team
  url: https://fondy.eu/

toolbar:
-
  name: Examples
  link: /examples/
-
  name: Signup
  link: https://bit.ly/fondy-payments


buttons:
  -
    name: View on GitHub
    link: https://github.com/cloudipsp/ipsp-js-sdk
  -
    name: Download .zip
    link: http://github.com/cloudipsp/ipsp-js-sdk/archive/master.zip
  -
    name: Download .tar.gz
    link: http://github.com/cloudipsp/ipsp-js-sdk/archive/master.tar.gz

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      sharethis: property=59ccda6b55a6eb001239a098&product=sticky-share-buttons
      image:
        path:  /assets/img/cover.jpg
        height: 1200
        width: 630